project:
  type: website
  output-dir: docs

website:
  title: "As Above / So Below"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: statements.qmd
        text: Who We Are

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

